# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
language: node_js
node_js:
  - 13
services:
  - docker
install:
# Build
script:
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
# Do similar for other three images
# Tagging
- docker tag udagram-api-feed dansoncp/udagram-api-feed:v4a
- docker tag udagram-api-user dansoncp/udagram-api-user:v4a
- docker tag udagram-frontend dansoncp/udagram-frontend:local
- docker tag udagram-reverseproxy dansoncp/udagram-reverseproxy:v4a
# Do similar for other three images
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push dansoncp/udagram-api-feed:v4a
- docker push dansoncp/udagram-api-user:v4a
- docker push dansoncp/udagram-frontend:local
- docker push dansoncp/udagram-reverseproxy:v4a
# Do similar for other three images done