apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
      - name: udagram-api-user
        image: 'dansoncp/udagram-api-user:v6'
        envFrom:
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
          - configMapRef:
              name: env-configmap
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "100m"
          limits:
            memory: "2000Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080