apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: 'dansoncp/reverseproxy:v6'
        envFrom:
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
          - configMapRef:
              name: env-configmap
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "100m"
          limits:
            memory: "2000Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
      restartPolicy: Always